// ===== EXPORT MODULE - PDF, DOCX, Print, Share, Backup =====

const Exporter = {
    esc(s) { if (!s) return ''; const d = document.createElement('div'); d.textContent = s; return d.innerHTML; },

    exportPDF(cvId) {
        const cv = Storage.getCV(cvId);
        if (!cv) { App.toast('CV not found', 'danger'); return; }
        this.printContent(CVMgr.renderCVHTML(cv), cv.name || 'CV');
    },

    printCV(cvId) { this.exportPDF(cvId); },

    printContent(html, title) {
        const existing = document.querySelector('.print-area');
        if (existing) existing.remove();
        const printDiv = document.createElement('div');
        printDiv.className = 'print-area';
        printDiv.innerHTML = html;
        document.body.appendChild(printDiv);
        window.print();
        setTimeout(() => printDiv.remove(), 2000);
    },

    exportDOCX(cvId) {
        const cv = Storage.getCV(cvId);
        if (!cv) { App.toast('CV not found', 'danger'); return; }
        const html = CVMgr.renderCVHTML(cv);
        const wrapped = `<!DOCTYPE html><html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><title>${this.esc(cv.name)}</title><style>body{font-family:Arial,sans-serif;font-size:11pt;color:#333;max-width:794px;margin:0 auto;padding:20px}h4{font-size:12pt;font-weight:bold;text-transform:uppercase;border-bottom:1px solid #999;margin-top:16px}</style></head><body>${html}</body></html>`;
        const blob = new Blob(['\ufeff' + wrapped], { type: 'application/msword' });
        this.downloadBlob(blob, `${cv.name || 'CV'}.doc`);
        App.toast('DOCX downloaded', 'success');
    },

    shareCV(cvId) {
        const cv = Storage.getCV(cvId);
        if (!cv) return;
        const profile = Storage.getProfile();
        if (navigator.share) {
            navigator.share({
                title: cv.name || 'My CV',
                text: `${profile.fullName || 'My'} CV - ${CVMgr.getTemplateName(cv.template)}`,
                url: window.location.href,
            }).catch(() => {});
        } else {
            // Fallback: copy to clipboard
            const text = `${profile.fullName || 'Applicant'} - CV (${CVMgr.getTemplateName(cv.template)}). Generated by Libra CareerForge.`;
            try { navigator.clipboard.writeText(text); App.toast('CV info copied to clipboard', 'success'); }
            catch (e) { App.toast('Sharing not supported. Use Print to save as PDF.', 'info'); }
        }
    },

    exportAppPack(jobId) {
        const job = Storage.getJob(jobId);
        if (!job || !job.pack) { App.toast('Application pack not found', 'danger'); return; }
        const p = job.pack;
        const profile = Storage.getProfile();
        let html = `<div style="max-width:794px;margin:0 auto;padding:20px;font-family:Arial,sans-serif;color:#333">
            <h1 style="font-size:18pt;text-align:center;border-bottom:2px solid #D4A72C;padding-bottom:8px">Application Pack</h1>
            <p style="text-align:center;color:#666">${this.esc(job.jobTitle)} at ${this.esc(job.company)}</p>
            <h2 style="font-size:14pt;color:#0B1F3A;margin-top:24px">Cover Letter</h2>
            <pre style="white-space:pre-wrap;font-family:Arial;font-size:11pt">${this.esc(p.coverLetter || '')}</pre>
            <h2 style="font-size:14pt;color:#0B1F3A;margin-top:24px">Application Email</h2>
            <pre style="white-space:pre-wrap;font-family:Arial;font-size:11pt">${this.esc(p.appEmail || '')}</pre>
            <h2 style="font-size:14pt;color:#0B1F3A;margin-top:24px">LinkedIn Message</h2>
            <pre style="white-space:pre-wrap;font-family:Arial;font-size:11pt">${this.esc(p.linkedinMessage || '')}</pre>
            <h2 style="font-size:14pt;color:#0B1F3A;margin-top:24px">Talking Points</h2>
            <pre style="white-space:pre-wrap;font-family:Arial;font-size:11pt">${this.esc(p.talkingPoints || '')}</pre>
        </div>`;
        this.printContent(html, 'Application Pack');
    },

    exportBackup() {
        const data = Storage.exportBackup();
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        this.downloadBlob(blob, `libra-careerforge-backup-${new Date().toISOString().split('T')[0]}.json`);
        App.toast('Backup exported', 'success');
    },

    importBackup(input) {
        const file = input.files[0];
        if (!file) return;
        const reader = new FileReader();
        reader.onload = (e) => {
            const success = Storage.importBackup(e.target.result);
            if (success) {
                App.toast('Backup imported successfully', 'success');
                App.applySettings();
                App.navigate('home');
            } else {
                App.toast('Invalid backup file', 'danger');
            }
        };
        reader.readAsText(file);
    },

    exportReport(type) {
        let html = '';
        const profile = Storage.getProfile();
        const cvs = Storage.getAllCVs();
        const jobs = Storage.getAllJobs();
        const apps = Storage.getAllApplications();

        const header = `<div style="max-width:794px;margin:0 auto;padding:20px;font-family:Arial,sans-serif;color:#333">
            <h1 style="font-size:18pt;color:#0B1F3A">Libra CareerForge Report</h1>
            <p style="color:#666">Generated: ${new Date().toLocaleDateString()}</p><hr style="border:none;border-top:2px solid #D4A72C;margin:12px 0">`;

        const footer = '</div>';

        if (type === 'cv-health') {
            html = header + '<h2 style="font-size:14pt">CV Health Report</h2>';
            cvs.forEach(cv => {
                const ats = Scoring.atsFormattingScore(cv);
                html += `<h3 style="font-size:12pt">${this.esc(cv.name)} — ATS: ${ats.score}%</h3><ul>`;
                ats.checks.forEach(c => { html += `<li style="font-size:11pt">${c.name}: ${c.status} — ${c.detail}</li>`; });
                html += '</ul>';
            });
            if (cvs.length === 0) html += '<p>No CVs available.</p>';
            html += footer;
        } else if (type === 'ats') {
            html = header + '<h2 style="font-size:14pt">ATS Report</h2>';
            cvs.forEach(cv => {
                const ats = Scoring.atsFormattingScore(cv);
                html += `<h3 style="font-size:12pt">${this.esc(cv.name)} — ${ats.score}%</h3><ul>`;
                ats.checks.forEach(c => { html += `<li style="font-size:11pt">${c.name}: ${c.status} — ${c.detail}</li>`; });
                html += '</ul>';
            });
            if (cvs.length === 0) html += '<p>No CVs available.</p>';
            html += footer;
        } else if (type === 'job-match') {
            html = header + '<h2 style="font-size:14pt">Job Match Report</h2>';
            jobs.forEach(job => {
                const score = job.matchScore;
                html += `<h3 style="font-size:12pt">${this.esc(job.jobTitle)} at ${this.esc(job.company)}</h3>`;
                if (score) {
                    html += `<p style="font-size:11pt">Overall Match: <strong>${score.overall}%</strong></p><ul>`;
                    html += `<li>Keyword: ${score.keyword.score}%</li><li>Skills: ${score.skills.score}%</li><li>Experience: ${score.experience.score}%</li><li>Education: ${score.education.score}%</li><li>Certifications: ${score.certification.score}%</li><li>ATS: ${score.atsFormatting.score}%</li>`;
                    html += '</ul>';
                } else { html += '<p>No match data available.</p>'; }
            });
            if (jobs.length === 0) html += '<p>No jobs analyzed.</p>';
            html += footer;
        } else if (type === 'application-activity') {
            html = header + '<h2 style="font-size:14pt">Application Activity Report</h2>';
            html += `<p style="font-size:11pt">Total Applications: ${apps.length}</p>`;
            const byStatus = {};
            apps.forEach(a => { byStatus[a.status] = (byStatus[a.status] || 0) + 1; });
            html += '<ul>';
            Object.entries(byStatus).forEach(([s, c]) => { html += `<li style="font-size:11pt">${s}: ${c}</li>`; });
            html += '</ul>';
            html += '<h3 style="font-size:12pt">Recent Applications</h3><ul>';
            apps.slice(0, 10).forEach(a => { html += `<li style="font-size:11pt">${this.esc(a.position)} at ${this.esc(a.company)} — ${a.status}</li>`; });
            html += '</ul>';
            if (apps.length === 0) html += '<p>No applications yet.</p>';
            html += footer;
        } else if (type === 'skills-gap') {
            html = header + '<h2 style="font-size:14pt">Skills Gap Report</h2>';
            const profileSkills = (profile.skills || []).map(s => typeof s === 'string' ? s : s.name).filter(Boolean);
            html += `<p style="font-size:11pt">Your skills: ${profileSkills.join(', ') || 'None listed'}</p>`;
            jobs.forEach(job => {
                const ji = job.extracted || {};
                const missing = (ji.allSkills || []).filter(s => !profileSkills.some(ps => ps.toLowerCase().includes(s) || s.includes(ps.toLowerCase())));
                html += `<h3 style="font-size:12pt">${this.esc(job.jobTitle)}</h3><p style="font-size:11pt">Missing skills: ${missing.join(', ') || 'None — all covered'}</p>`;
            });
            if (jobs.length === 0) html += '<p>No jobs analyzed for gap comparison.</p>';
            html += footer;
        }

        this.printContent(html, 'Report');
    },

    downloadBlob(blob, filename) {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        setTimeout(() => URL.revokeObjectURL(url), 1000);
    },
};
